INSERT INTO categories (nom, description,date_creation)
VALUES
  ('Electronique', 'Produits électroniques tels que les téléphones, ordinateurs, etc.','2023-02-02'),
  ('Vêtements', 'Vêtements pour hommes, femmes et enfants','2023-02-02'),
  ('Livres', 'Livres pour tous les âges et genres','2023-02-02'),
  ('Maison et Jardin', 'Articles pour la maison et le jardinage','2023-02-02'),
  ('Beauté et Soins', 'Produits de beauté et soins personnels','2023-02-02'),
  ('Alimentation', 'Aliments pour toutes les occasions','2023-02-02'),
  ('Sports et Loisirs', 'Équipements pour le sport et les loisirs','2023-02-02'),
  ('Jouets et Jeux', 'Jouets et jeux pour enfants et adultes','2023-02-02'),
  ('Automobile', 'Pièces et accessoires pour voitures','2023-02-02'),
  ('Musique', 'Instruments de musique et accessoires','2023-02-02'),
  ('Voyage', 'Voyages, hôtels, billets avion et autres produits liés aux voyages','2023-02-02'),
  ('Meubles', 'Meubles pour la maison et le bureau','2023-02-02'),
  ('Bricolage', 'Outils et matériaux pour le bricolage','2023-02-02'),
  ('Animaux', 'Produits pour animaux de compagnie','2023-02-02'),
  ('Électroménager', 'Appareils électroménagers pour la maison','2023-02-02'),
  ('Jeux vidéo', 'Jeux vidéo pour toutes les plateformes','2023-02-02'),
  ('Art et Artisanat', 'Art et produits artisanaux','2023-02-02'),
  ('Aliments pour animaux', 'Aliments pour animaux de compagnie','2023-02-02'),
  ('Fleurs et Plantes', 'Fleurs et plantes pour intérieur et extérieur','2023-02-02'),
  ('Informatique', 'Matériel et logiciels informatiques','2023-02-02'),
  ('High-tech', 'Produits high-tech tels que les appareils photo, drones, etc.','2023-02-02'),
  ('Automobile', 'Voitures, camions et autres véhicules','2023-02-02'),
  ('Bijoux', 'Bijoux en or, argent, diamants, etc.','2023-02-02'),
  ('Fournitures de bureau', 'Fournitures de bureau telles que des stylos, du papier, etc.','2023-02-02'),
  ('Art de la table', 'Articles pour la cuisine et la salle à manger','2023-02-02'),
  ('Luminaires', 'Luminaires pour la maison et le jardin','2023-02-02'),
  ('Jardinage', 'Outils et matériaux pour le jardinage','2023-02-02'),
  ('Puériculture', 'Produits pour les bébés et les enfants','2023-02-02'),
  ('Santé et bien-être', 'Produits pour la santé et le bien-être','2023-02-02'),
  ('Outils', 'Outils pour le bricolage et le jardinage','2023-02-02'),
  ('Beauté et soins personnels', 'Produits de beauté et de soins personnels','2023-02-02'),
  ('Sport et fitness', 'Equipements et vêtements pour le sport et le fitness','2023-02-02'),
  ('Maison et décoration', 'Articles pour la maison et la décoration','2023-02-02'),
  ('Bagages', 'Bagages pour les voyages','2023-02-02'),
  ('Audio et vidéo', 'Produits audio et vidéo pour la maison','2023-02-02'),
  ('Livres', 'Livres pour tous les genres et tous les âges','2023-02-02'),
  ('Jouets et jeux', 'Jouets et jeux pour les enfants','2023-02-02'),
  ('Chaussures', 'Chaussures pour hommes, femmes et enfants','2023-02-02'),
  ('Vêtements', 'Vêtements pour hommes, femmes et enfants','2023-02-02'),
  ('Accessoires de mode', 'Accessoires de mode tels que des bijoux, des lunettes, etc.','2023-02-02'),
  ('Mobilier', 'Meubles pour la maison et le bureau','2023-02-02'),
  ('Vélos et accessoires', 'Vélos et accessoires pour les cyclistes','2023-02-02'),
  ('Voyages', 'Produits pour les voyages','2023-02-02'),
  ('Jeux vidéo', 'Jeux vidéo pour les consoles et les ordinateurs','2023-02-02'),
  ('Instruments de musique', 'Instruments de musique tels que les guitares, les pianos, etc.','2023-02-02'),
  ('Cuisine et arts culinaires', 'Produits pour la cuisine et les arts culinaires','2023-02-02'),
  ('Bricolage', 'Outils et matériaux pour le bricolage','2023-02-02'),
  ('Animaux', 'Produits pour les animaux domestiques','2023-02-02'),
  ('Fleurs et plantes', 'Fleurs et plantes pour la maison et le jardin','2023-02-02'),
  ('Aliments et boissons', 'Aliments et boissons pour le petit déjeuner, le déjeuner et le dîner','2023-02-02');


