INSERT INTO produits (nom, description, prix,date_creation)
VALUES
  ('Ordinateur portable', 'Ordinateur portable de haute qualité avec des caractéristiques puissantes', 999,'2023-02-02'),
  ('Smartphone', 'Smartphone avec un écran de haute résolution et des fonctionnalités avancées', 799),'2023-02-02',
  ('Téléviseur', 'Téléviseur LED de haute qualité avec une image claire et brillante', 599,'2023-02-02'),
  ('Tablette', 'Tablette légère et portable avec une longue durée de vie de la batterie', 399,'2023-02-02'),
  ('Appareil photo numérique', 'Appareil photo numérique professionnel avec des fonctionnalités avancées', 749,'2023-02-02'),
  ('Casque audio', 'Casque audio sans fil confortable avec un son de qualité supérieure', 199,'2023-02-02'),
  ('Enceinte Bluetooth', 'Enceinte Bluetooth portable avec un son puissant et clair', 99,'2023-02-02'),
  ('Lampe de bureau', 'Lampe de bureau moderne et élégante avec un design soigné', 49,'2023-02-02'),
  ('Aspirateur', 'Aspirateur puissant et silencieux avec des filtres de haute qualité', 199,'2023-02-02'),
  ('Fer à repasser', 'Fer à repasser de haute qualité avec un design ergonomique', 79,'2023-02-02'),
  ('Grille-pain', 'Grille-pain compact avec des fonctionnalités avancées', 29,'2023-02-02'),
  ('Machine à café', 'Machine à café professionnelle avec une vapeur puissante et une buse de distribution de lait', 199,'2023-02-02'),
  ('Réfrigérateur', 'Réfrigérateur moderne avec un espace de stockage élargi et une température constante', 799,'2023-02-02'),
  ('Lave-vaisselle', 'Lave-vaisselle silencieux et efficace avec un nettoyage en profondeur', 599,'2023-02-02'),
  ('Lave-linge', 'Lave-linge de haute qualité avec une capacité de charge importante et des programmes de lavage avancés', 499,'2023-02-02'),
  ('Chauffage dappoint', 'Chauffage dappoint efficace et économique avec un design moderne', 149,'2023-02-02'),
  ('Ventilateur', 'Ventilateur silencieux avec une vitesse réglable et un design élégant', 59,'2023-02-02'),
  ('Aspirateur à main', 'Aspirateur à main léger et maniable avec une aspiration puissante', 59,'2023-02-02'),
  ('Micro-ondes', 'Micro-ondes avec un design moderne et une fonction de décongélation rapide', 49,'2023-02-02'),
  ('Sèche-cheveux', 'Sèche-cheveux professionnel avec une vitesse et une température réglables', 59,'2023-02-02');
